direcciones = {
    "192.168.1.11": {
        "descripcion": "eje 1 chica 1",
        "eje": 1,
        "tipoPantalla": 1,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show  --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.12": {
        "descripcion": "eje 1 chica 2",
        "eje": 1,
        "tipoPantalla": 1,
        "numero": 2,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.13": {
        "descripcion": "eje 1 mediana 1",
        "eje": 1,
        "tipoPantalla": 2,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.14": {
        "descripcion": "eje 1 mediana 2",
        "eje": 1,
        "tipoPantalla": 2,
        "numero": 2,
        "angulo": 270,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show  --video-filter=transform --transform-type=270 --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.15": {
        "descripcion": "eje 1 grande",
        "eje": 1,
        "tipoPantalla": 3,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.21": {
        "descripcion": "eje 2 chica 1",
        "eje": 2,
        "tipoPantalla": 1,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mov'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.22": {
        "descripcion": "eje 2 chica 2",
        "eje": 2,
        "tipoPantalla": 1,
        "numero": 2,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.23": {
        "descripcion": "eje 2 mediana 1",
        "eje": 2,
        "tipoPantalla": 2,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.24": {
        "descripcion": "eje 2 mediana 2",
        "eje": 2,
        "tipoPantalla": 2,
        "numero": 2,
        "angulo": 90,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.25": {
        "descripcion": "eje 2 grande",
        "eje": 2,
        "tipoPantalla": 3,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mov'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.31": {
        "descripcion": "eje 3 chica 1",
        "eje": 3,
        "tipoPantalla": 1,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.32": {
        "descripcion": "eje 3 chica 2",
        "eje": 3,
        "tipoPantalla": 1,
        "numero": 2,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.33": {
        "descripcion": "eje 3 mediana 1",
        "eje": 3,
        "tipoPantalla": 2,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.34": {
        "descripcion": "eje 3 mediana 2",
        "eje": 3,
        "tipoPantalla": 2,
        "numero": 2,
        "angulo": 270,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show  --video-filter=transform --transform-type=270 --play-and-exit '",
        "comandoSufijo": ".mp4'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --video-filter=transform --transform-type=90 --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.35": {
        "descripcion": "eje 3 grande",
        "eje": 3,
        "tipoPantalla": 3,
        "numero": 1,
        "angulo": 0,
        "comandoPrefijo": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijo": ".mov'",
        "comandoGenerativa": "vlc --fullscreen --no-video-deco --qt-minimal-view --no-sub-autodetect-file --no-video-title-show --play-and-exit '",
        "comandoSufijoGenerativa": ".mov'",
    },
    "192.168.1.50": {
        "tipo": "dev",
        "descripcion": "macbook aaron",
        "eje": 0,
        "tipoPantalla": 0,
        "numero": 0
    },
    "192.168.1.51": {
        "descripcion": "ipad aaron",
        "eje": 0,
        "tipoPantalla": 0,
        "numero": 0
    },
    "192.168.1.52": {
        "descripcion": "192.168.1.52",
        "eje": 0,
        "tipoPantalla": 0,
        "numero": 0
    },
    "192.168.1.53": {
        "descripcion": "macbook janis",
        "eje": 0,
        "tipoPantalla": 0,
        "numero": 0
    },
}